# fly.toml app configuration file generated for snack-dz on 2023-06-17T16:37:50-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "snack-dz"
primary_region = "gru"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
